language: generic

sudo: false

addons:
  apt:
    packages:
    - mplayer
    - swftools
    - rtmpdump

env:
  global:
    VIMPROC_ROOT=/tmp/vimproc.vim

install:
  - git clone --depth 1 --branch v1.5.3 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis
  - git clone --depth 1 --branch ver.9.3 --single-branch https://github.com/Shougo/vimproc.vim.git /tmp/vimproc.vim &&
    cd /tmp/vimproc.vim &&
    make &&
    cd $TRAVIS_BUILD_DIR
  # install newest version of vim
  - git clone https://github.com/vim/vim /tmp/vim &&
    cd /tmp/vim &&
    git checkout $(git describe --tags --abbrev=0) &&
    ./configure --prefix=$HOME/vim-git &&
    make &&
    make install &&
    cd $TRAVIS_BUILD_DIR
  - export THEMIS_VIM=$HOME/vim-git/bin/vim

before_script:
  - $HOME/vim-git/bin/vim --version

script:
  - /tmp/vim-themis/bin/themis --reporter spec

